# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call('_scAI_eigenMapMatMult', PACKAGE = 'scAI', A, B)
}

eigenMapMatcrossprod <- function(A, B) {
    .Call('_scAI_eigenMapMatcrossprod', PACKAGE = 'scAI', A, B)
}

eigenMapMattcrossprod <- function(A, B) {
    .Call('_scAI_eigenMapMattcrossprod', PACKAGE = 'scAI', A, B)
}

